### ISSUE TITLE
Could this workshop be also done on an Odroid H4 Ultra or is there modifications needed ?

### ISSUE THREAD

**Issue by AkechiShiro** [9elements/osf-coreboot-workshop#2]
Or is that not recommended but may/may not work/brick hardware ?

**Comment by LeanSheng** [comment]
Hi @AkechiShiro , sorry for not responding, was busy and away for some time - yes it should work and able to boot on H4 Ultra. Are you able to try on it? do you need any help?

**Comment by LeanSheng** [comment]
The diff of H4 Utra and H4+ is the CPU chip, and so far I checked the ohter peripherals are the same. Since we are able to boot to H4+, I dont see any problem with H4 Ultra :)

**Comment by AkechiShiro** [comment]
Thanks for the information, I haven't ordered yet but if I do, I'll provide an update thanks!

I believe, this issue can be closed for now.

**Comment by LeanSheng** [comment]
got it, just let us know if you need any help in flashing or building the image, so we can improve our documentation.

**Comment by AkechiShiro** [comment]
Sorry for asking this now, is there any information to solder the kit (RPI Pico) that was given during the workshop ?

**Comment by LeanSheng** [comment]
> Sorry for asking this now, is there any information to solder the kit (RPI Pico) that was given during the workshop ?

@MDr164

**Comment by MDr164** [comment]
I think it's overdue to update the README both here and in the Picoprog repos. And yes it works just as well on the H4 Ultra, it's the exact same PCB as the H4+ except using a different SoC than the regular H4 and H4+ but that one works with the same FSP and I think even same coreboot image as the H4+.

**Comment by AkechiShiro** [comment]
Yes probably this would fix this issue : https://github.com/9elements/picoprog/issues/18

**Comment by MDr164** [comment]
Yep. I'll update the documentation this week and merge the picoprog hardware repo into the software (main) repo which also includes all the schematics and such of the carrier board for the pico. Btw you can also use the pico without the carrier, you can instead use a bunch of jumper/dupont wires for the clamp. But I'll add all that to the README.

**Comment by AkechiShiro** [comment]
Hey @MDr164 just would like to know if you have started working on the update, maybe you could create a PR on the readme of picocom even if it's not finished, so we would have some instructions but not all yet ?

**Comment by MDr164** [comment]
I'm currently doing that and updating everything on that repo and afterwards update the README here a bit as well.
